language: generic

matrix:
  include:
    - os: linux
      python: 3.6
      env:
        - PYTHON_VERSION=3.6

before_install:

    # Use utf8 encoding. Should be default, but this is insurance
    # against future changes

    - export PYTHONIOENCODING=UTF8
    - export MPLBACKEND=Agg

    # Install miniconda following instructions at
    # http://conda.pydata.org/docs/travis.html
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
      fi
    - bash miniconda.sh -b -p $HOME/miniconda
    - . $HOME/miniconda/etc/profile.d/conda.sh
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda  # get latest conda version
    # Useful for debugging any issues with conda
    - conda info -a
    - git fetch --tags

install:
    - conda env create --file environment.yml
    - conda activate cta-benchmarks

after_script:
    - conda deactivate

#after_success:
